# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CQN Winter School 2024 - Exploring and Designing Quantum Networks via Digital Twin Simulations
author: Dirk Englund, Hyeongrak Choi, Prajit Dhara

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto #auto or force or cache or 'off'
  timeout: 30

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

#Avoid unwanted files for build
only_build_toc_files: true
  
# Information about where the book exists on the web
repository:
  url                       : https://github.com/pr4jitd/2024.CQNSchool.DigitalTwin  # Online location of your book
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    mathjax_config:
      tex:
        macros:
          "ket"  : ["\\left|{#1}\\right\\rangle", 1]
          "bra"  : ["\\left\\langle{#1}\\right|", 1]
          "braket" : ["\\left\\langle{#1}\\middle|{#2}\\right\\rangle", 2]
          "adagger" : ["\\hat{a}^{\\dagger}"]
          "ahat" : ["\\hat{a}"]
          "bdagger" : ["\\hat{b}^{\\dagger}"]
          "bhat" : ["\\hat{b}"]
          "cdagger" : ["\\hat{c}^{\\dagger}"]
          "chat" : ["\\hat{c}"]
          "ddagger" : ["\\hat{d}^{\\dagger}"]
          "dhat" : ["\\hat{d}"]
          "edagger" : ["\\hat{e}^{\\dagger}"]
          "ehat" : ["\\hat{e}"]
          "fdagger" : ["\\hat{f}^{\\dagger}"]
          "fhat" : ["\\hat{f}"]
          "gdagger" : ["\\hat{g}^{\\dagger}"]
          "ghat" : ["\\hat{g}"]
          "hdagger" : ["\\hat{h}^{\\dagger}"]
          "hhat" : ["\\hat{h}"]
          "gtwo" : ["g^{(2)}"]
          "H" : ["\\ket{H}"]
          "V" : ["\\ket{V}"]
          "D" : ["\\ket{D}"]
          "AD" : ["\\ket{AD}"]
  
launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  colab_url: "https://colab.research.google.com"
 
